plugins {
    id 'com.android.application'
}

android {
    namespace 'com.fillipe.webmapper'
    compileSdk 35

    defaultConfig {
        applicationId 'com.fillipe.idledexcompanion'
        minSdk 24
        targetSdk 29
        versionCode 24
        versionName '2.2.0'
    }

    buildFeatures {
        buildConfig true
    }

    lint {
        disable 'ExpiredTargetSdkVersion'
        abortOnError false
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20240303'
}
