plugins {
    id 'com.android.application'
}

android {
    namespace 'com.fillipe.webmapper'
    compileSdk 35

    defaultConfig {
        applicationId 'com.fillipe.webmapper'
        minSdk 24
        targetSdk 35
        versionCode 20
        versionName '2.0.0'
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
